### PR TITLE
Refactored version

### PR DESCRIPTION
**Pull request by anxdpanic**

### CODE REVIEW

**Comment by anxdpanic** [comment]
@mikesilvo164 
It looks like you've been away a while, as seen above I'm working on a large update.
Is this something you're interested in? If preferred I can move this over to my repo if you're inactive, or create a fork.

**Comment by mikesilvo164** [comment]
I'm still around just have had way less free time. I stumbled my way through updating this to Python 3 and it looks like you actually know what you're doing lol

If you'd like to take over maintaining this project I'm sure the skinning community and myself would be grateful :)

I can also give you collab access to this repository if interested.

**Comment by anxdpanic** [comment]
hah, I've had a few runs at the py2 -> 3 thing :)

Keeping the script here would be great. 
I can take over maintaining it if you'd prefer, Collab would be enough to get that done :)

Just wanted to make sure where I was putting the effort in the end :D

**Comment by BobCratchett** [comment]
Hi, and let’s say upfront - this is just fantastic work.

For the record, I’m the idiot who originally created this script. I did so as someone with some idea of programming, but literally no understanding of Python. Hence why the script became the absolute nightmare of code that it did.

I’ll be frank, I don’t have the time or the health to actually look at the changes that you’re making, but each PR is hitting my e-Mail. Whilst I don’t want for a second to disparage anyone who has contributed to this script over the years (every contribution has made for a more functional script though not necessarily a better written one), it’s obvious we’ve finally got someone who actually knows Python broadly, and, as such - and based purely on each PRs description - it feels like you may be the one who makes this not just a functional script, but an actually well-coded one!

Hope you’re going to be around for the long-term, and best of luck with where you take this script. And even if it’s just this one modernisation that you do before you move onto pastures new, you’re still setting the script up to be able to be maintained and improved by Python-scripters going forth.

With Thanks
 Ignoble/Unfledged/BobCratchett

**Comment by Ch1llb0** [comment]
> Hope you’re going to be around for the long-term, and best of luck with where you take this script. And even if it’s just this one modernisation that you do before you move onto pastures new, you’re still setting the script up to be able to be maintained and improved by Python-scripters going forth.

I sincerely hope for the same! It's great to finally have been able to ask the seemingly right one to invest (even more) knowledge and precious time to make this already amazing script better and bring it into 2021... As the current maintainer of the OSMC Skin and therefore someone working with code @BobCratchett was originally responsible for, I'm humbled by what you guys are doing... Thanks for your work! :)

**Comment by BobCratchett** [comment]
> therefore someone working with code @BobCratchett was originally responsible for

For any code I’m responsible for … my sincerest apologies :)

**Comment by anxdpanic** [comment]
Thanks! :D
There is no doubt that it's an amazing script and very functional, and that is all thanks to you guys and the others that have worked on it. So, thank you as well for that!

I don't see myself going anywhere soon, and will be trying to stay on top of maintenance when it's it required 👍 
I've added some GitHub actions, one of which runs some basic checks on new PR's (kodi-addon-checker, pylint, and isort). So, that should hopefully help keep the code more maintainable going forward :)

And, sorry (all the watchers too) for the e-mail influx, it _should_ start slowing down a bit now :)

If you have any questions about the PR/stuff I'm doing to the script, don't hesitate :)
Cheers!

**Comment by anxdpanic** [comment]
The bulk of the work should be done. Will merge this, add Weblate and work on more targeted PR's, so testing can start :D

**Pull request merged**
